added sentry and logging (#19)
cryptic-game/python3-lib pull request #20
Opened 2019-07-23 16:11 UTC by SpartanerSpaten

## Description
Added Sentry at important point where error may occur the stack-trace and given relevant data to find the origin of the bug will be piped into a log file. Which should be than sit in a docker volume. 

## Related Issue
#19 

## Motivation and Context
Test Driven Development

## How Has This Been Tested?
tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x ] My code follows the code style of this project.
- [ x ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2019-07-24 20:05 UTC, SpartanerSpaten commented
adding sdk

2019-07-25 14:34 UTC, SpartanerSpaten commented
This introduces new Environment Variables PATH_LOGFILE, DSN, RELEASE

2019-07-25 19:04 UTC, felixevers requested changes
Thank you!
Please improved the code based on this review within a few days.

2019-07-25 19:04 UTC, felixevers commented on README.md
> -### Environment variables
Is there a reason for this deletion?

2019-07-25 19:04 UTC, felixevers commented on cryptic/__init__.py
> +
No whitespace at here, please?

2019-07-25 19:04 UTC, felixevers commented on cryptic/__init__.py
> +                database=_config["MYSQL_DATABASE"],
Not necessary...

2019-07-25 19:04 UTC, use-to commented on cryptic/__init__.py
> +        self._database: DatabaseWrapper = DatabaseWrapper()
This is explicit... -> No typing (optional)

2019-07-25 19:04 UTC, use-to commented on cryptic/__init__.py
> +        self._sentry: Sentry = Sentry(name)
This is explicit... -> No typing (optional)

2019-07-25 19:04 UTC, use-to commented on cryptic/__init__.py
> +                        self.__send({"tag": tag, "ms": frame["ms"], "data": {"error": "unknown_service"}})
Expand this statement, please!

2019-07-25 19:04 UTC, use-to commented on setup.py
> +)
<Tab> here, please!

2019-07-25 19:04 UTC, use-to commented on setup.py
> +    packages=find_packages(),
Unnecessary

2019-07-25 19:17 UTC, SpartanerSpaten commented on cryptic/__init__.py
> +        self._sentry: Sentry = Sentry(name)
Typing == fuck yeah

2019-07-25 19:17 UTC, SpartanerSpaten commented on cryptic/__init__.py
> +        self._database: DatabaseWrapper = DatabaseWrapper()
Typing == fuck yeah

2019-07-25 19:37 UTC, SpartanerSpaten commented on setup.py
> +    packages=find_packages(),
needed for pypi complete config

2019-07-25 19:38 UTC, SpartanerSpaten commented on README.md
> -### Environment variables
yeah will add docu and this table back in

2019-07-25 20:28 UTC, SpartanerSpaten commented on cryptic/__init__.py
> +                        self.__send({"tag": tag, "ms": frame["ms"], "data": {"error": "unknown_service"}})
What do you mean with "Expand this statement" ... should I log more Information or just code clean up @use-to

2019-07-26 20:41 UTC, SpartanerSpaten commented on setup.py
> +)
What do you mean ?

2019-07-26 21:01 UTC, felixevers requested changes
Better, but just respect my feedback to this pr.
So i dont want to discuss about unnecessary typings at here...

Some little fixes should be done!

2019-07-26 21:01 UTC, felixevers commented on README.md
Can you link the example.py?
```suggestion
## Quick Start
You can follow the [example.py](https://github.com/cryptic-game/python3-lib/blob/master/example.py) to create your first microservice.
```

2019-07-26 21:01 UTC, felixevers commented on cryptic/__init__.py
> +                        self.__send({"tag": tag, "ms": frame["ms"], "data": {"error": "unknown_service"}})
You can wrap the dict over multiple lines.

2019-07-26 21:01 UTC, felixevers commented on setup.py
> +)
Indent this!

2019-07-27 13:28 UTC, SpartanerSpaten commented on cryptic/__init__.py
> +                        self.__send({"tag": tag, "ms": frame["ms"], "data": {"error": "unknown_service"}})
black wants it this way.

2019-07-27 13:32 UTC, SpartanerSpaten commented
@use-to I am using the [black linter](https://github.com/psf/black) .... and the style changes you suggest are not conform with this pep8 enforcing tool

2019-07-27 13:45 UTC, SpartanerSpaten commented on README.md
done

2019-07-27 14:51 UTC, felixevers approved these changes
Nice! Thank you!

2019-07-27 14:55 UTC, merged